### ISSUE TITLE
Open old and new Realm files

### ISSUE THREAD

**Issue by kneth** [realm/realm-browser-osx#87] opened 2015-10-15 14:31 UTC
Related to #85: when we introduce null support, the Realm file format is changed. But it would be great if older Realm files can be opened too.

**Comment by TimOliver** [comment] 2015-10-15 17:26
@kneth Thanks for that Kenneth! It's already on my list! :)

I was looking at the `SharedGroup` header file, and it looks like Realm can't open files from a previous version if you don't let it run the automatic update process (It will simply throw an exception). Can you confirm that?

**Comment by astigsen** [comment] 2015-10-15 21:26
It would be great if it in those cases could just show a dialog asking if you want to upgrade the file. If they reply no, it would be fine to say that they can't open it and should use an older version of the browser.

**Comment by kneth** [comment] 2015-10-16 08:16
@TimOliver Yes, your observation is true: it is not possible to open a v2 file, and you should first try opening by disallow upgrade, catch the exception and show the dialog as @astigsen suggest. I do find it a bit cumbersome to have two different versions of the browser installed. In the case, the user doesn't wish to upgrade, we could copy the file, upgrade it and show the temporary copy. Of course, the user cannot modify the file as we delete it when the browser closes it.

**Comment by TimOliver** [comment] 2015-11-16 17:00
For the initial release of Realm 0.96, I implemented the logic we discussed here where a file is 'tested' against that upgrade requirement before it is opened, and a dialog box warning the user appears. (PR: https://github.com/realm/realm-browser-osx/pull/91). At the moment, if the user refuses to upgrade the file, they simply cannot open it in that version of the Browser.

Now I can come back and spend a bit more time on this, having a temporary, unmodifiable duplicate of the Realm file that we can display would certainly mitigate the majority of the use cases developers would have in needing to open older files. We could probably even simply add a button to that upgrade prompt stating 'Open as Read-Only'.

What are your thoughts on that?

**Comment by kneth** [comment] 2015-11-17 07:29
"Open as Read-Only" might be fine as it implies that the file isn't migrated to the new file format.

**Comment by TimOliver** [comment] 2016-06-08 07:06
I'm going through some of the old Browser issues marked as pending and doing some spring cleaning. :)

Now that we've hit 1.0, and the 'optional upgrade' mechanism has been integrated for a while, does anyone think it would still be necessary to add an additional 'open as read only' mode for non-upgraded Realm files?

**Comment by kneth** [comment] 2016-06-08 07:49
Sounds like it is safe to close the issue

**Comment by wmfgithub** [comment] 2016-06-16 03:03
'default' is at an older file format version and must be upgraded before it can be opened. Would you like to proceed?  the detail description is ' If the file is upgraded, it will no longer be compatible with older versions of Realm. File format upgrades are permanent and cannot be undone'.

**Comment by TimOliver** [comment] 2016-06-17 19:00
Hi @wmfgithub!

Yes, that's correct. When an older Realm file is opened in the Browser, it needs to be updated to the latest Realm file format before it can be edited. This thread was discussing whether we needed an alternative option to open files in a read-only mode without performing the upgrade, but we've decided not to do that for the time being. :)

**Closed by TimOliver** 2016-06-17 19:00 UTC
Labels: S:Waiting For User, T:Enhancement
