### ISSUE TITLE
Get .realm from the device automatically

### ISSUE THREAD

**Issue by kubatru** [realm/realm-browser-osx#124] opened 2016-02-08 10:56 UTC
I know how to get realm database from the current running device, but I'm wonder if there is some automatic way to do that (e.g. run script during the build phase to get the last .realm database from the previous run).

**Comment by TimOliver** [comment] 2016-02-08 17:13
Hi @kubatru!

Just to be sure, do you mean from an actual device, and not just the iOS Simulator?

We just had a quick discussion about this. Since your test apps expose sandbox access to Xcode, it MIGHT be possible write a script to have Xcode perform a manual dump of the user data for your app.

That's not confirmed at all though. We'd need to do some thorough research to see if it actually is feasible. :)

**Comment by jpsim** [comment] 2016-02-08 17:45
As far as I know, there's no officially supported way to programmatically get files off an iOS device.

We could embed a webserver in `Realm.framework` for use for debugging, but that seems inappropriate in almost every other situation.

**Comment by kubatru** [comment] 2016-02-09 13:15
Thank you guy, fingers crossed

**Comment by TimOliver** [comment] 2016-03-30 05:21
I'm going through and cleaning out the Browser's issue list.

I researched it too, and there's definitely not an official way to access files on iOS device from an OS X app. It would need to be a custom implementation, most likely entirely on the device's side, which is a bit out of scope for the Browser.

For the time being, I would recommend trying out Flipboard's FLEX project. We recently contributed the ability to directly inspect Realm files on the device through it. :)

https://github.com/Flipboard/FLEX

We'll keep looking at ways to make it easier to debug Realm files directly from the device.

**Closed by TimOliver** 2016-03-30 05:21 UTC
Labels: enhancement, pending

**Comment by dmorrow** [comment] 2017-02-17 14:28
I'd be interested in this as well.  A socket connection like [Reveal App](https://revealapp.com) uses, active only if a param is turned on or a library included for a build configuration would be very helpful.

**Comment by TimOliver** [comment] 2017-02-17 19:41
If the Realm is synchronized through the Realm Mobile Platform, you can view the contents of the Realm in realtime in the Browser by connecting to the Object Server. :)

If you wanted to do something like Reveal (Which ostensibly runs a server on the device to serve the data), you could use something like [GCDServer](https://github.com/swisspol/GCDWebServer) or [iExplorer](https://macroplant.com/iexplorer) to expose remote file access.
