### ISSUE TITLE
Browser crash

### ISSUE THREAD

**Issue by morten-krogh** [realm/realm-browser-osx#233] opened 2016-11-07 10:15 UTC
I have had the browser open for a several days. I did not use it actively. Suddenly it
reported an internal error.

The browser is version 2.0.1

The stack trace is below.

Exception Name: NSInvalidArgumentException
Description: -[_MDItem valueForAttribute:]: unrecognized selector sent to instance 0x618000030d80
User Info: (null)

0 CoreFoundation 0x00007fffbe4977bb __exceptionPreprocess + 171
1 libobjc.A.dylib 0x00007fffd2c04a2a objc_exception_throw + 48
2 CoreFoundation 0x00007fffbe517d84 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
3 CoreFoundation 0x00007fffbe40afc3 forwarding + 1059
4 CoreFoundation 0x00007fffbe40ab18 _CF_forwarding_prep_0 + 120
5 Realm Browser 0x000000010f3177fc -[RLMApplicationDelegate updateFileItems] + 1761
6 Realm Browser 0x000000010f31613f -[RLMApplicationDelegate realmQueryNote:] + 285
7 CoreFoundation 0x00007fffbe4246ac CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER + 12
8 CoreFoundation 0x00007fffbe4245ab _CFXRegistrationPost + 427
9 CoreFoundation 0x00007fffbe424312 ___CFXNotificationPost_block_invoke + 50
10 CoreFoundation 0x00007fffbe3e2a32 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 2018
11 CoreFoundation 0x00007fffbe3e1a1b _CFXNotificationPost + 667
12 Foundation 0x00007fffbfe0f0e3 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
13 CoreFoundation 0x00007fffbe4246ac CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER + 12
14 CoreFoundation 0x00007fffbe4245ab _CFXRegistrationPost + 427
15 CoreFoundation 0x00007fffbe424312 ___CFXNotificationPost_block_invoke + 50
16 CoreFoundation 0x00007fffbe3e2a32 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 2018
17 CoreFoundation 0x00007fffbe3e1a1b _CFXNotificationPost + 667
18 CoreFoundation 0x00007fffbe477a11 CFNotificationCenterPostNotificationWithOptions + 113
19 Metadata 0x00007fffbf7744ef _postQueryNotification + 222
20 Metadata 0x00007fffbf73e470 _pushNotification + 112
21 Metadata 0x00007fffbf774267 sendNotificationLocked + 1397
22 Metadata 0x00007fffbf73dfe8 processUpdatesLocked + 1539
23 Metadata 0x00007fffbf736c6b tryProcessUpdates + 661
24 Foundation 0x00007fffbff97614 -[NSMetadataQuery _update] + 146
25 CoreFoundation 0x00007fffbe4246ac CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER + 12
26 CoreFoundation 0x00007fffbe4245ab _CFXRegistrationPost + 427
27 CoreFoundation 0x00007fffbe424312 ___CFXNotificationPost_block_invoke + 50
28 CoreFoundation 0x00007fffbe3e2a32 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 2018
29 CoreFoundation 0x00007fffbe3e1a1b _CFXNotificationPost + 667
30 CoreFoundation 0x00007fffbe477a11 CFNotificationCenterPostNotificationWithOptions + 113
31 Metadata 0x00007fffbf7718b7 ___pushAsyncNotification_block_invoke + 228
32 CoreFoundation 0x00007fffbe42e3cc CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK + 12
33 CoreFoundation 0x00007fffbe40f6f4 __CFRunLoopDoBlocks + 356
34 CoreFoundation 0x00007fffbe40f236 __CFRunLoopRun + 1894
35 CoreFoundation 0x00007fffbe40e874 CFRunLoopRunSpecific + 420
36 HIToolbox 0x00007fffbd9aef6c RunCurrentEventLoopInMode + 240
37 HIToolbox 0x00007fffbd9aeda1 ReceiveNextEventCommon + 432
38 HIToolbox 0x00007fffbd9aebd6 _BlockUntilNextEventMatchingListInModeWithFilter + 71
39 AppKit 0x00007fffbc0a55f5 _DPSNextEvent + 1093
40 AppKit 0x00007fffbc7b58eb -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1637
41 AppKit 0x00007fffbc099fbd -[NSApplication run] + 926
42 AppKit 0x00007fffbc064a8a NSApplicationMain + 1237
43 libdyld.dylib 0x00007fffd34e0255 start + 1

**Comment by stel** [comment] 2017-06-26 09:14
Unfortunately I'm still not able to reproduce this crash. Will close this issue for now. If it still exists we will get it via crash reports on HockeyApp.

**Closed by stel** 2017-06-26 09:14 UTC
Labels: S:P1 Backlog, T:Bug-Crash
